In [1]:
import torch
print(torch.__version__)  # 2.6.0+cu124
print(torch.cuda.is_available())  # True
print(torch.version.cuda)  # 12.4
print(torch.cuda.get_device_name(0))  # NVIDIA GeForce RTX 4060 (无错)

2.6.0+cu124
True
12.4
NVIDIA GeForce RTX 4060 Laptop GPU


In [3]:
print(torch.cuda.device_count())
torch.cuda.current_device()


1


0

TENSOR 的GPU计算

In [5]:
x = torch.tensor([1, 2, 3])
print(x)
x = x.cuda(0)
print(x)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
# 方法1：直接指定
x = torch.tensor([1, 2, 3], device=device)
print(x)
# 方法2：使用.to()方法
x = torch.tensor([1, 2, 3]).to(device)
print(x)

y = x ** 2
print(y)

tensor([1, 2, 3])
tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3], device='cuda:0')
tensor([1, 2, 3], device='cuda:0')
tensor([1, 4, 9], device='cuda:0')


模型的GPU计算

In [6]:
import torch.nn as nn
net = nn.Linear(3, 1)
list(net.parameters())[0].device
net.cuda()
list(net.parameters())[0].device
x = torch.rand(2,3).cuda()
net(x)

tensor([[0.1335],
        [0.4975]], device='cuda:0', grad_fn=<AddmmBackward0>)