1.读写 TENSOR

In [1]:
import torch
from torch import nn

# 创建Tensor并保存
x = torch.ones(3)
torch.save(x, 'x.pt')

# 从文件加载Tensor
x2 = torch.load('x.pt')
print(x2)  # 输出: tensor([1., 1., 1.])
print(torch.equal(x, x2))  # 输出: True

# 保存Tensor列表
y = torch.zeros(4)
torch.save([x, y], 'xy_list.pt')

# 加载Tensor列表
xy_list = torch.load('xy_list.pt')
print(xy_list)  # 输出: [tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]
print(f"列表长度: {len(xy_list)}")  # 输出: 列表长度: 2

# 保存Tensor字典
torch.save({'x': x, 'y': y}, 'xy_dict.pt')

# 加载Tensor字典
xy_dict = torch.load('xy_dict.pt')
print(xy_dict)  # 输出: {'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}
print(f"x: {xy_dict['x']}")  # 输出: x: tensor([1., 1., 1.])
print(f"y: {xy_dict['y']}")  # 输出: y: tensor([0., 0., 0., 0.])

tensor([1., 1., 1.])
True
[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]
列表长度: 2
{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}
x: tensor([1., 1., 1.])
y: tensor([0., 0., 0., 0.])


2.读写模型
    （1）state_dict
    （2）优化器state_dict

In [3]:
import torch
import torch.nn as nn

class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(3, 2)  # 可学习参数
        self.act = nn.ReLU()           # 无参数
        self.output = nn.Linear(2, 1)  # 可学习参数
    
    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)

net = MLP()
net.state_dict()  # 获取模型参数字典



OrderedDict([('hidden.weight',
              tensor([[ 0.1077, -0.3335, -0.4982],
                      [ 0.5070, -0.4183, -0.3231]])),
             ('hidden.bias', tensor([0.2592, 0.0888])),
             ('output.weight', tensor([[-0.2139, -0.5938]])),
             ('output.bias', tensor([0.5768]))])

In [4]:
#优化器state_dict()
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'maximize': False,
   'foreach': None,
   'differentiable': False,
   'fused': None,
   'params': [0, 1, 2, 3]}]}

2.保存和加载模型
    (1)保存和加载 state_dict (推荐方式)
    (2)保存和加载整个模型

In [ ]:
#1.保存和加载 state_dict (推荐方式)
import torch
import torch.nn as nn

# 保存模型
torch.save(model.state_dict(), 'model.pth')  # 推荐使用 .pt 或 .pth 后缀

# 加载模型
model = TheModelClass(*args, **kwargs)  # 必须先创建模型实例
model.load_state_dict(torch.load('model.pth'))
model.eval()  # 设置为评估模式

#2.保存和加载整个模型
torch.save(model, PATH)
model = torch.load(PATH)

#验证
X = torch.randn(2, 3)
Y = net(X)
PATH = "./net.pt"
torch.save(net.state_dict(), PATH)
net2 = MLP()
net2.load_state_dict(torch.load(PATH))
Y2 = net2(X)
Y2 == Y

tensor([[True],
        [True]])